// Generated by jextract

package sun.font.fontmanager;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class hb_jdk_p_h {

    static final SymbolLookup SYMBOL_LOOKUP
            = SymbolLookup.loaderLookup().or(Linker.nativeLinker().defaultLookup());

    hb_jdk_p_h() {
        // Should not be called directly
    }

    public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
    public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
    public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
    public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
    public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
    public static final ValueLayout.OfInt C_LONG = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfDouble C_LONG_DOUBLE = ValueLayout.JAVA_DOUBLE;

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
         String traceArgs = Arrays.stream(args)
                       .map(Object::toString)
                       .collect(Collectors.joining(", "));
         System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static MemoryLayout[] inferVariadicLayouts(Object[] varargs) {
        MemoryLayout[] result = new MemoryLayout[varargs.length];
        for (int i = 0; i < varargs.length; i++) {
            result[i] = variadicLayout(varargs[i].getClass());
        }
        return result;
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MethodHandle downcallHandleVariadic(String name, FunctionDescriptor baseDesc, MemoryLayout[] variadicLayouts) {
        FunctionDescriptor variadicDesc = baseDesc.appendArgumentLayouts(variadicLayouts);
        Linker.Option fva = Linker.Option.firstVariadicArg(baseDesc.argumentLayouts().size());
        return SYMBOL_LOOKUP.find(name)
                .map(addr -> Linker.nativeLinker().downcallHandle(addr, variadicDesc, fva)
                        .asSpreader(Object[].class, variadicLayouts.length))
                .orElse(null);
    }

    // Internals only below this point

    private static MemoryLayout variadicLayout(Class<?> c) {
        // apply default argument promotions per C spec
        // note that all primitives are boxed, since they are passed through an Object[]
        if (c == Boolean.class || c == Byte.class || c == Character.class || c == Short.class || c == Integer.class) {
            return JAVA_INT;
        } else if (c == Long.class) {
            return JAVA_LONG;
        } else if (c == Float.class || c == Double.class) {
            return JAVA_DOUBLE;
        } else if (MemorySegment.class.isAssignableFrom(c)) {
            return ADDRESS;
        }
        throw new IllegalArgumentException("Invalid type for ABI: " + c.getTypeName());
    }

    private static class jdk_hb_shape$constants {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            hb_jdk_p_h.C_INT,
            hb_jdk_p_h.C_FLOAT,
            hb_jdk_p_h.C_POINTER,
            hb_jdk_p_h.C_POINTER,
            hb_jdk_p_h.C_POINTER,
            hb_jdk_p_h.C_INT,
            hb_jdk_p_h.C_INT,
            hb_jdk_p_h.C_INT,
            hb_jdk_p_h.C_INT,
            hb_jdk_p_h.C_INT,
            hb_jdk_p_h.C_FLOAT,
            hb_jdk_p_h.C_FLOAT,
            hb_jdk_p_h.C_INT,
            hb_jdk_p_h.C_INT,
            hb_jdk_p_h.C_POINTER,
            hb_jdk_p_h.C_POINTER
        );

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(
                    hb_jdk_p_h.findOrThrow("jdk_hb_shape"),
                    DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int jdk_hb_shape(float ptSize, float *matrix, void *pFace, unsigned short *chars, int len, int script, int offset, int limit, int baseIndex, float startX, float startY, int flags, int slot, hb_font_funcs_t *font_funcs, store_layoutdata_func_t store_layout_data_upcall)
     * }
     */
    public static FunctionDescriptor jdk_hb_shape$descriptor() {
        return jdk_hb_shape$constants.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int jdk_hb_shape(float ptSize, float *matrix, void *pFace, unsigned short *chars, int len, int script, int offset, int limit, int baseIndex, float startX, float startY, int flags, int slot, hb_font_funcs_t *font_funcs, store_layoutdata_func_t store_layout_data_upcall)
     * }
     */
    public static MethodHandle jdk_hb_shape$handle() {
        return jdk_hb_shape$constants.HANDLE;
    }
    /**
     * {@snippet lang=c :
     * int jdk_hb_shape(float ptSize, float *matrix, void *pFace, unsigned short *chars, int len, int script, int offset, int limit, int baseIndex, float startX, float startY, int flags, int slot, hb_font_funcs_t *font_funcs, store_layoutdata_func_t store_layout_data_upcall)
     * }
     */
    public static int jdk_hb_shape(float ptSize, MemorySegment matrix, MemorySegment pFace, MemorySegment chars, int len, int script, int offset, int limit, int baseIndex, float startX, float startY, int flags, int slot, MemorySegment font_funcs, MemorySegment store_layout_data_upcall) {
        var mh$ = jdk_hb_shape$constants.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("jdk_hb_shape", ptSize, matrix, pFace, chars, len, script, offset, limit, baseIndex, startX, startY, flags, slot, font_funcs, store_layout_data_upcall);
            }
            return (int)mh$.invokeExact(ptSize, matrix, pFace, chars, len, script, offset, limit, baseIndex, startX, startY, flags, slot, font_funcs, store_layout_data_upcall);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class HBCreateFontFuncs$constants {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            hb_jdk_p_h.C_POINTER,
            hb_jdk_p_h.C_POINTER,
            hb_jdk_p_h.C_POINTER,
            hb_jdk_p_h.C_POINTER,
            hb_jdk_p_h.C_POINTER,
            hb_jdk_p_h.C_POINTER
        );

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(
                    hb_jdk_p_h.findOrThrow("HBCreateFontFuncs"),
                    DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * hb_font_funcs_t *HBCreateFontFuncs(hb_font_get_nominal_glyph_func_t nominal_fn, hb_font_get_variation_glyph_func_t variation_fn, hb_font_get_glyph_h_advance_func_t h_advance_fn, hb_font_get_glyph_v_advance_func_t v_advance_fn, hb_font_get_glyph_contour_point_func_t contour_pt_fn)
     * }
     */
    public static FunctionDescriptor HBCreateFontFuncs$descriptor() {
        return HBCreateFontFuncs$constants.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * hb_font_funcs_t *HBCreateFontFuncs(hb_font_get_nominal_glyph_func_t nominal_fn, hb_font_get_variation_glyph_func_t variation_fn, hb_font_get_glyph_h_advance_func_t h_advance_fn, hb_font_get_glyph_v_advance_func_t v_advance_fn, hb_font_get_glyph_contour_point_func_t contour_pt_fn)
     * }
     */
    public static MethodHandle HBCreateFontFuncs$handle() {
        return HBCreateFontFuncs$constants.HANDLE;
    }
    /**
     * {@snippet lang=c :
     * hb_font_funcs_t *HBCreateFontFuncs(hb_font_get_nominal_glyph_func_t nominal_fn, hb_font_get_variation_glyph_func_t variation_fn, hb_font_get_glyph_h_advance_func_t h_advance_fn, hb_font_get_glyph_v_advance_func_t v_advance_fn, hb_font_get_glyph_contour_point_func_t contour_pt_fn)
     * }
     */
    public static MemorySegment HBCreateFontFuncs(MemorySegment nominal_fn, MemorySegment variation_fn, MemorySegment h_advance_fn, MemorySegment v_advance_fn, MemorySegment contour_pt_fn) {
        var mh$ = HBCreateFontFuncs$constants.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("HBCreateFontFuncs", nominal_fn, variation_fn, h_advance_fn, v_advance_fn, contour_pt_fn);
            }
            return (MemorySegment)mh$.invokeExact(nominal_fn, variation_fn, h_advance_fn, v_advance_fn, contour_pt_fn);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class HBCreateFace$constants {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            hb_jdk_p_h.C_POINTER,
            hb_jdk_p_h.C_POINTER
        );

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(
                    hb_jdk_p_h.findOrThrow("HBCreateFace"),
                    DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * hb_face_t *HBCreateFace(GetTableDataFn *get_data_upcall_fn)
     * }
     */
    public static FunctionDescriptor HBCreateFace$descriptor() {
        return HBCreateFace$constants.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * hb_face_t *HBCreateFace(GetTableDataFn *get_data_upcall_fn)
     * }
     */
    public static MethodHandle HBCreateFace$handle() {
        return HBCreateFace$constants.HANDLE;
    }
    /**
     * {@snippet lang=c :
     * hb_face_t *HBCreateFace(GetTableDataFn *get_data_upcall_fn)
     * }
     */
    public static MemorySegment HBCreateFace(MemorySegment get_data_upcall_fn) {
        var mh$ = HBCreateFace$constants.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("HBCreateFace", get_data_upcall_fn);
            }
            return (MemorySegment)mh$.invokeExact(get_data_upcall_fn);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class HBDisposeFace$constants {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            hb_jdk_p_h.C_POINTER
        );

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(
                    hb_jdk_p_h.findOrThrow("HBDisposeFace"),
                    DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void HBDisposeFace(hb_face_t *face)
     * }
     */
    public static FunctionDescriptor HBDisposeFace$descriptor() {
        return HBDisposeFace$constants.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void HBDisposeFace(hb_face_t *face)
     * }
     */
    public static MethodHandle HBDisposeFace$handle() {
        return HBDisposeFace$constants.HANDLE;
    }
    /**
     * {@snippet lang=c :
     * void HBDisposeFace(hb_face_t *face)
     * }
     */
    public static void HBDisposeFace(MemorySegment face) {
        var mh$ = HBDisposeFace$constants.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("HBDisposeFace", face);
            }
            mh$.invokeExact(face);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

