// Generated by jextract

package sun.font.fontmanager;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef int (*store_layoutdata_func_t)(int, int, int, float, float, float, int, int, hb_glyph_info_t *, hb_glyph_position_t *)
 * }
 */
public class store_layoutdata_func_t {

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(int slot, int baseIndex, int offset, float startX, float startY, float devScale, int charCount, int glyphCount, MemorySegment glyphInfo, MemorySegment glyphPos);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        hb_jdk_p_h.C_INT,
        hb_jdk_p_h.C_INT,
        hb_jdk_p_h.C_INT,
        hb_jdk_p_h.C_INT,
        hb_jdk_p_h.C_FLOAT,
        hb_jdk_p_h.C_FLOAT,
        hb_jdk_p_h.C_FLOAT,
        hb_jdk_p_h.C_INT,
        hb_jdk_p_h.C_INT,
        hb_jdk_p_h.C_POINTER,
        hb_jdk_p_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = hb_jdk_p_h.upcallHandle(store_layoutdata_func_t.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(store_layoutdata_func_t.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,int slot, int baseIndex, int offset, float startX, float startY, float devScale, int charCount, int glyphCount, MemorySegment glyphInfo, MemorySegment glyphPos) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, slot, baseIndex, offset, startX, startY, devScale, charCount, glyphCount, glyphInfo, glyphPos);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

